{
 "title": "Boot mixed Errors",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total cloud-init DNS setting dumb ccount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cloud_init_dns_setting_dump_count"
    }
   ]
  },
  {
   "title": "Total I/O Error count for blk update request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "IO_error_blk_update_request_count"
    }
   ]
  },
  {
   "title": "SQASHFS read data failure count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "squashfs_read_data_failed_count"
    }
   ]
  },
  {
   "title": "ISOFS read i-node blk error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ISOFS_read_inode_blk_error_count"
    }
   ]
  },
  {
   "title": "NO_REBOOT flag reset failure count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "no_reboot_flag_reset_failure_count"
    }
   ]
  }
 ]
}